name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run tests
        run: poetry run pytest -v